repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  slf4j_api: org.slf4j:slf4j-api:jar:1.6.1
  getopt4j: org.realityforge.getopt4j:getopt4j:jar:1.2
  json_simple: com.googlecode.json-simple:json-simple:jar:1.1
  log4j: log4j:log4j:jar:1.2.8
  logback_classic: ch.qos.logback:logback-classic:jar:0.9.29
  logback_core: ch.qos.logback:logback-core:jar:0.9.29
